# Generated by Django 5.1.7 on 2025-04-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.AddField(
            model_name='project',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_projects', to='api.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='min_participants',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
