# Generated by Django 5.1.7 on 2025-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_participants',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
