# Generated by Django 5.1.7 on 2025-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_creator_project_curator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('curator', 'Куратор'), ('student', 'Студент')], default='student', max_length=8),
        ),
    ]
