# Generated by Django 5.1.7 on 2025-04-27 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectskill',
            options={'ordering': ['skill__name']},
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='projectskill_level_range_1_5'),
        ),
    ]
