# Generated by Django 5.1.7 on 2025-05-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projectskill_options_alter_projectskill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
    ]
