# Generated by Django 5.1.7 on 2025-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='level_required',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
