# Generated by Django 5.1.7 on 2025-05-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
