# Generated by Django 5.1.7 on 2025-04-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='level_required',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='project',
        ),
        migrations.AddField(
            model_name='requirement',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('skill', 'level'), name='unique_skill_level'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(related_name='projects', through='api.ProjectRequirement', to='api.requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together={('project', 'requirement')},
        ),
    ]
