# Generated by Django 5.2 on 2025-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentskill_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='graph_representation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
