# Generated by Django 5.2 on 2025-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_skill_graph_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='graph_representation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
