# Generated by Django (modified manually)

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_skill_graph_representation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectskill',
            name='projectskill_level_range_1_5',
        ),
    ]
