# Generated by Django 5.2 on 2025-06-18 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_projectskill_projectskill_level_range_1_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskill',
            name='level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 0), ('level__lte', 1)), name='projectskill_level_range_0_1'),
        ),
    ]
