# Generated by Django 5.2 on 2025-06-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_projectskill_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('path', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='api.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='api.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['from_skill', 'to_skill'], name='api_skillpa_from_sk_33ad46_idx'), models.Index(fields=['distance'], name='api_skillpa_distanc_a3e3a5_idx')],
                'unique_together': {('from_skill', 'to_skill')},
            },
        ),
    ]
